### ISSUE TITLE
doesn't want to enable

### ISSUE THREAD

**Issue by trikop** [Domiis/dmc-headwars#1]
[23:56:11] [Server thread/INFO]: [DMC-HeadWars] Enabling DMC-HeadWars v1.1-SNAPSHOT
[23:56:11] [Server thread/ERROR]: Error occurred while enabling DMC-HeadWars v1.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: dev/geco/gholo/api/GHoloAPI
	at com.github.domiis.Main.onEnable(Main.java:38) ~[DMC-HeadWars.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.geco.gholo.api.GHoloAPI
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:174) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
[23:56:11] [Server thread/INFO]: [DMC-HeadWars] Disabling DMC-HeadWars v1.1-SNAPSHOT
[23:56:11] [Server thread/INFO]: [DMC-HeadWars] Plugin was successfully turned off

**Comment by Domiis** [comment]
Hi! You don't have GHolo plugin. If you don't want to have it - disable support in config. (support.GHolo: false)
Config was made for me, so this plugin is required by default. I don't know why I didn't change it. Sorry.

**Comment by trikop** [comment]
The GHolo plugin doesn't seem to really be around anymore since the [spigotmc ](https://www.spigotmc.org/resources/gholo-the-new-modern-holo-plugin-1-8-x-1-16-x.70913/)page for it is just gone,  
Adding support for like https://www.spigotmc.org/resources/decentholograms-1-8-1-19-papi-support-no-dependencies.96927/ or really just another one in general would be nice :))

**Comment by trikop** [comment]
Actually, I found the GHolo plugin on some random site, but it didn't seem to work hmm

**Comment by Domiis** [comment]
You're right, GHolo has disappeared from spigotmc.  I'll try to add support DecentHolograms today. Let me know if it works!

**Comment by Domiis** [comment]
Corrected.
