### ISSUE TITLE
leaving a game after joining it gives this error in the console

### ISSUE THREAD

**Issue by trikop** [Domiis/dmc-headwars#2]
[18:36:24] [Server thread/INFO]: trikop issued server command: /hw join default
[18:36:30] [Server thread/INFO]: trikop issued server command: /hw leave
[18:36:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hw' in plugin DMC-HeadWars v1.1-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:311) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2385) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1784]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.cancel()" because "this.watekID" is null
	at com.github.domiis.gra.G_Gra.zastopuj(G_Gra.java:500) ~[DMC-HeadWars.jar:?]
	at com.github.domiis.gra.G_Gra.usun(G_Gra.java:541) ~[DMC-HeadWars.jar:?]
	at com.github.domiis.komendy.Dolaczanie.opusc(Dolaczanie.java:93) ~[DMC-HeadWars.jar:?]
	at com.github.domiis.komendy.GlownaKomenda.onCommand(GlownaKomenda.java:79) ~[DMC-HeadWars.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by Domiis** [comment]
Corrected.
